baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'kcp – a Kubernetes-like multi-tenant control plane'

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
